### ISSUE TITLE
Upload to NPM

### ISSUE THREAD

**Issue by vpillinger** [cdwv/oas3-api-snippet-enricher#1]
It is possible to upload this package to NPM?

Its nice to use the snippet generator as a CLI interface for integration with build tools.

Thanks!

**Comment by Arvoreen** [comment]
+1

**Comment by andrzejwp** [comment]
Thanks for reporting
@vpillinger @Arvoreen this issue is currently worked on by @KarolNet 
we will let you know once completed

**Comment by KarolNet** [comment]
Hi, npm package are done.
Try ` npm i snippet-enricher-cli` to install.

**Comment by vpillinger** [comment]
Thanks!
