### ISSUE TITLE
Make Languages a CLI option

### ISSUE THREAD

**Issue by vpillinger** [cdwv/oas3-api-snippet-enricher#2]
It would be nice to specify which languages to generate snippets for customization via the CLI.

Something like
```
node index.js --targets="python, shell_curl" openapi.json > openapi-with-examples.json
```

**Comment by KarolNet** [comment]
Hi, option `--target` are added.

**Comment by vpillinger** [comment]
Thankyou!

**Comment by greatvovan** [comment]
> Hi, option `--target` are added.

@KarolNet excuse me, where is the list of available targets?

**Comment by greatvovan** [comment]
Ah, they are probably in https://github.com/ErikWittern/openapi-snippet...
