### ISSUE TITLE
Error during installation with node:alpine docker image

### ISSUE THREAD

**Issue by edoeel** [cdwv/oas3-api-snippet-enricher#5]
Hi,
I get an error when I try to install your npm package.
That's my `node` image:
`FROM node:12.16.2-alpine3.11`

<img width="655" alt="Screenshot 2020-05-01 at 22 28 03" src="https://user-images.githubusercontent.com/38187989/80839875-5b6b4e80-8bfc-11ea-96b7-3beb25863119.png">

Here the log file
[2020-05-01T20_27_36_369Z-debug.log](https://github.com/cdwv/oas3-api-snippet-enricher/files/4566202/2020-05-01T20_27_36_369Z-debug.log)

**Comment by KarolNet** [comment]
Hi, please try again. The error should no longer occur.

**Comment by edoeel** [comment]
Hi KarolNet, it works perfectly.
Thank you

**Comment by andrzejwp** [comment]
Thanks @edoardomistretta and apologies - the package was pinned to a branch, which was since then merged. Let us know if you have any other issues or need help. 

We're also open for contributions ;-)
