### ISSUE TITLE
Require(...) is not a function 

### ISSUE THREAD

**Issue by RolphH** [cdwv/oas3-api-snippet-enricher#7]
When (as documented) running `./node_modules/.bin/snippet-enricher-cli --input=....` there is an error:

`
require('./../index.js')();
                        ^
TypeError: require(...) is not a function
`

Removing the () from the require fixed this issue.

**Comment by andrzejwp** [comment]
@RolphH can you please open a PR for this?

**Comment by thblckjkr** [comment]
I have the same problem, to solve it i tried to use any of the older versions (0.3 - 0.5) and it didn't work.

I guess has something to do with my node version `v14.3.0` but i am not really sure.

I solved it with a script in my project repo, containing the following code, to solve the problem without modifying the code in `node_modules`

```js
#!/usr/bin/env node
require('../node_modules/snippet-enricher-cli/index');
```
